/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package core

import (
	e "ksogit.kingsoft.net/docmini/fx/xfx/econtext"
	"ksogit.kingsoft.net/docmini/fx/xfx/el"
	"ksogit.kingsoft.net/docmini/mapis/tag1"
	"ksogit.kingsoft.net/docmini/mapis/tag1/httpdef"
	"ksogit.kingsoft.net/docmini/mapis/tag1/schemas"
)

var _ httpdef.Time
var _ schemas.Time
var _ el.XError
var _ e.EContext

type Tag1CoreNoopImpl struct {
}

func NewCoreNoopImpl() tag1.CoreAPI {
	return &Tag1CoreNoopImpl{}
}
