/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package translations

import (
	"embed"
	"encoding/json"
	"fmt"
	"ksogit.kingsoft.net/docmini/fx/xfx/i18n"
)

//go:embed asset
var FS embed.FS

func init() {
	dirName := "asset"
	locales, err := FS.ReadDir(dirName)
	if err != nil {
		panic(err)
	}
	for _, locale := range locales {
		fileName := fmt.Sprintf("%s/%s/%s.json", dirName, locale.Name(), locale.Name())
		data, err := FS.ReadFile(fileName)
		if err != nil {
			panic(err)
		}
		var dict map[string]string
		err = json.Unmarshal(data, &dict)
		if err != nil {
			panic(err)
		}
		i18n.MustSet(locale.Name(), dict)
	}
}
