/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package test

import (
	common_m2 "ksogit.kingsoft.net/docmini/mapis/m2/mock"
	"tmp/modules/impl/base"
)

func initBaseModules() base.BaseModules {
	base := base.BaseModules{
		M2Module: common_m2.NewCoreNoopImpl(),
	}

	return base
}
