// Code generated by xfx; DO NOT EDIT.

package middlewares

import (
	"ksogit.kingsoft.net/docmini/fx/xfx"
)

type M1 struct {
}

func (m *M1) Name() string {
	return "m1"
}

func init() {
	xfx.RegisterMiddleware(&M1{})
}
