/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package ep

import (
	"fmt"
	"net/http"
	"regexp"
	"strings"

	"ksogit.kingsoft.net/docmini/fx/xfx"
	"ksogit.kingsoft.net/docmini/fx/xfx/el"
	"ksogit.kingsoft.net/docmini/fx/xfx/endpoint"
	"ksogit.kingsoft.net/docmini/fx/xfx/rw"

	"ksogit.kingsoft.net/docmini/fx/xfx/econtext"
	"ksogit.kingsoft.net/docmini/mapis/tag1/httpdef"

	srv "tmp/http/services"
	"tmp/modules"
)

type GetSchema struct {
	xfx.EndpointBase
}

func (h *GetSchema) Name() string {
	return "GetSchema"
}

func (h *GetSchema) Module() string {
	return "tag1"
}

func (h *GetSchema) Method() string {
	return "GET"
}

func (h *GetSchema) URL() string {
	return "/path/{get}/path2"
}

func parseGetSchemaRequest(w http.ResponseWriter, r *http.Request) (*httpdef.GetSchemaRequest, error) {
	var err error
	_ = err
	in := httpdef.NewGetSchemaRequest()
	err = rw.ParsePath(r, in)
	if err != nil {
		return nil, el.Adapt(err)
	}
	err = rw.ParseQuery(r, in)
	if err != nil {
		return nil, el.Adapt(err)
	}
	return in, nil
}

func (h *GetSchema) Endpoint(app xfx.App) endpoint.Endpoint {
	callService := srv.NewGetSchemaService(modules.Get(app))
	return func(w http.ResponseWriter, r *http.Request) error {
		in, err := parseGetSchemaRequest(w, r)
		if err != nil {
			return rw.WriteError(w, r, el.Adapt(err))
		}
		in.EscapeStrings()
		out, err := callService(econtext.ToEContext(r.Context()), in)
		if err != nil {
			return rw.WriteError(w, r, err)
		}
		if out != nil {
			out.I18n(r.Context())
		}
		return rw.WriteJson(w, 200, out)
	}
}

func init() {
	var cheker = func(endpointSchema xfx.EndpointSchema) {
		method := endpointSchema.Method()
		if strings.ToLower(method) != "get" && strings.ToLower(method) != "post" {
			panic(fmt.Sprintf("endpoint's method must to be \"GET\" or \"POST\",but \" get \"%s\"", method))
		}
		url := endpointSchema.URL()
		matched, _ := regexp.MatchString(`^/[a-z0-9/_{}]+$`, url)
		if !matched {
			panic(fmt.Sprintf("endpoint's  url is invalid,%s", url))
		}
		if url[len(url)-1] == '\\' {
			panic(fmt.Sprintf("endpoint's  url is invalid,%s", url))
		}
	}
	cheker(&GetSchema{})
	xfx.RegisterEndpoint(xfx.PUBLIC, &GetSchema{})
}
