components:
  responses:
    error:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: error
  schemas:
    error:
      properties:
        code:
          $ref: '#/components/schemas/errorCode'
        detail:
          allOf:
          - $ref: '#/components/schemas/error'
          description: more error
          nullable: true
          x-order: 2
        msg:
          description: error message
          type: string
          x-order: 1
      required:
      - code
      - msg
    errorCode:
      description: |
        errors
          * '400000002' - parameter format error
      enum:
      - 400000002
      type: integer
      x-enum:
      - CodeParamFormatError
    get_schema_response_body:
      allOf:
      - $ref: '#/components/schemas/response_common'
      properties:
        data:
          allOf:
          - $ref: '#/components/schemas/schema_name'
          nullable: true
          x-omitempty: true
          x-order: 0
    response_common:
      description: response_common
      properties:
        code:
          description: code
          format: int64
          type: integer
          x-order: 0
        detail:
          description: detail
          maxLength: 1024
          type: string
          x-order: 2
        msg:
          description: msg
          maxLength: 1024
          type: string
          x-order: 1
      required:
      - code
      - msg
    schema_name:
      properties:
        options:
          description: 字段描述
          maxLength: 1024
          type: string
          x-order: 0
      required:
      - options
    t2: {}
info:
  title: tag1
  version: v1
openapi: 3.0.0
paths:
  /path/{get}/path2:
    get:
      operationId: get_schema
      parameters:
      - in: path
        name: get
        required: true
        schema:
          maxLength: 1024
          type: string
          x-type: int64
      - in: query
        name: offset
        required: true
        schema:
          format: int64
          minimum: 0
          type: integer
      - in: query
        name: limit
        required: true
        schema:
          format: int64
          maximum: 1000
          minimum: 1
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/get_schema_response_body'
          description: "200"
        default:
          $ref: '#/components/responses/error'
      x-nodoc: false
      x-nonstandard: false
servers:
- url: url1
tags:
- name: tag1
- name: tag2
