/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package httpdef

import (
	"html"
	"time"

	"ksogit.kingsoft.net/docmini/fx/xfx/econtext"
	"tmp/schemas"
)

var _ = html.EscapeString
var _ schemas.Time
var _ = time.Parse

type GetSchemaRequest struct {
	Get    int64 `json:"-" path:"get,required"`
	Offset int64 `json:"-" query:"offset,required" validate:"min=0"`
	Limit  int64 `json:"-" query:"limit,required" validate:"min=1,max=1000"`
}

func NewGetSchemaRequest() *GetSchemaRequest {
	v := &GetSchemaRequest{}
	return v
}

func (r *GetSchemaRequest) EscapeStrings() {
}

type GetSchemaResponse = schemas.GetSchemaResponseBody

var NewGetSchemaResponse = schemas.NewGetSchemaResponseBody

type GetSchemaFunc func(econtext.EContext, *GetSchemaRequest) (*GetSchemaResponse, error)
