/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package modules

import (
	e "ksogit.kingsoft.net/docmini/fx/xfx/econtext"
	"ksogit.kingsoft.net/docmini/fx/xfx/el"
	"ksogit.kingsoft.net/docmini/mapis/interceptor"
	common_tag1 "ksogit.kingsoft.net/docmini/mapis/tag1"
	"ksogit.kingsoft.net/docmini/mapis/tag1/httpdef"
	"ksogit.kingsoft.net/docmini/mapis/tag1/schemas"
)

var _ e.EContext
var _ el.XError
var _ httpdef.Time
var _ schemas.Time
var _ common_tag1.CoreAPI
var _ interceptor.ApiInfo

func chainUnaryGetSchemaInterceptor(interceptors []common_tag1.GetSchemaInterceptor) common_tag1.GetSchemaInterceptor {
	if len(interceptors) == 0 {
		return nil
	}
	return func(ctx e.EContext, r *httpdef.GetSchemaRequest, apiInfo *interceptor.ApiInfo, handler common_tag1.GetSchemaHandler) (*httpdef.GetSchemaResponse, el.XError) {
		var state struct {
			i    int
			next common_tag1.GetSchemaHandler
		}
		state.next = func(ctx e.EContext, r *httpdef.GetSchemaRequest) (*httpdef.GetSchemaResponse, el.XError) {
			if state.i == len(interceptors)-1 {
				return interceptors[state.i](ctx, r, apiInfo, handler)
			}
			state.i++
			return interceptors[state.i-1](ctx, r, apiInfo, state.next)
		}
		return state.next(ctx, r)
	}
}
