/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package modules

import (
	"ksogit.kingsoft.net/docmini/fx/xfx"
	common_tag1 "ksogit.kingsoft.net/docmini/mapis/tag1"
	"tmp/modules/impl/core"
	"tmp/modules/impl/http"
)

type Tag1Module struct {
	AppContext xfx.App
	Interceptors

	Tag1CoreImpl *core.Tag1CoreImpl
	Tag1HttpImpl *http.Tag1HttpImpl
}

var _ common_tag1.CoreAPI = &Tag1Module{}

func (c *Tag1Module) Name() string {
	return "tag1"
}

func (c *Tag1Module) Init(app xfx.App) {
	c.AppContext = app

	coreImpl := core.NewImpl(app, c.Name(), c.DependOn()...)
	c.Tag1CoreImpl = coreImpl
	c.Tag1HttpImpl = http.NewImpl(app, c.Name(), coreImpl, c.DependOn()...)

	c.InitInterceptors(app)
}

func (c *Tag1Module) Term(app xfx.App) {
}

func (c *Tag1Module) DependOn() []string {
	return []string{
		"m2",
	}
}

func Get(app xfx.App) *Tag1Module {
	return app.Module("tag1").(*Tag1Module)
}

var m = &Tag1Module{}

func init() {
	xfx.RegisterModule(m)
}
