/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package modules

import (
	e "ksogit.kingsoft.net/docmini/fx/xfx/econtext"
	"ksogit.kingsoft.net/docmini/fx/xfx/el"
	"ksogit.kingsoft.net/docmini/mapis/interceptor"
	common_tag1 "ksogit.kingsoft.net/docmini/mapis/tag1"
	"ksogit.kingsoft.net/docmini/mapis/tag1/httpdef"
	"ksogit.kingsoft.net/docmini/mapis/tag1/schemas"
)

var _ = httpdef.Time{}
var _ = schemas.Time{}
var _ common_tag1.CoreAPI = &Tag1Module{}
var _ common_tag1.HttpAPI = &Tag1Module{}
var _ e.EContext
var _ el.XError
var _ interceptor.Interceptor

func (m *Tag1Module) GetSchema(ctx e.EContext, r *httpdef.GetSchemaRequest) (*httpdef.GetSchemaResponse, el.XError) {
	if m.GetSchemaUnaryInt == nil {
		return m.Tag1HttpImpl.GetSchema(ctx, r)
	}
	apiInfo := &interceptor.ApiInfo{
		ModuleName: "Tag1",
		ApiName:    "GetSchema",
	}
	return m.GetSchemaUnaryInt(ctx, r, apiInfo, m.Tag1HttpImpl.GetSchema)
}
