/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package modules

import (
	"ksogit.kingsoft.net/docmini/fx/xfx"
	common_tag1 "ksogit.kingsoft.net/docmini/mapis/tag1"
)

type Interceptors struct {
	GetSchemaUnaryInt         common_tag1.GetSchemaInterceptor
	chainGetSchemaInterceptor []common_tag1.GetSchemaInterceptor
}

func (m *Tag1Module) InitInterceptors(app xfx.App) {

	for _, interceptor := range common_tag1.GlobalCommInterceptors() {
		inter := interceptor.Interceptor(app, m)
		if inter != nil {
			m.chainGetSchemaInterceptor = append(m.chainGetSchemaInterceptor, common_tag1.ToGetSchemaInterceptor(inter))
		}
	}
	for _, interceptor := range common_tag1.GlobalGetSchemaInterceptors() {
		inter := interceptor.Interceptor(app, m)
		if inter != nil {
			m.chainGetSchemaInterceptor = append(m.chainGetSchemaInterceptor, inter)
		}
	}
	m.GetSchemaUnaryInt = chainUnaryGetSchemaInterceptor(m.chainGetSchemaInterceptor)
}
