/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package schemas

import (
	"fmt"
)

func checkErrorCode(errCode int64) {
	strcode := fmt.Sprintf("%d", errCode)
	if len(strcode) != 9 {
		panic(fmt.Sprintf("invalid error code, invalid length : %d", errCode))
	}
}

func init() {
}
