/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package schemas

import (
	"context"
	"encoding/json"
	"fmt"
	"html"
	"strings"
	"time"

	"ksogit.kingsoft.net/docmini/fx/xfx/conv"
	"ksogit.kingsoft.net/docmini/fx/xfx/el"
	"ksogit.kingsoft.net/docmini/fx/xfx/i18n"
	xfx_json "ksogit.kingsoft.net/docmini/fx/xfx/json"
	"ksogit.kingsoft.net/docmini/fx/xfx/validator"
)

var _ = time.Parse
var _ = html.EscapeString
var _ = validator.CheckRequired
var _ = json.Marshal
var _ = xfx_json.Marshal
var _ = fmt.Println
var _ = conv.ParseInt64
var _ = strings.NewReader
var _ = el.New
var _ = i18n.Translate

type GetSchemaResponseBody struct {
	Code   int64       `json:"code"`
	Data   *SchemaName `json:"data,omitempty"`
	Detail string      `json:"detail" validate:"omitempty,max=1024"`
	Msg    string      `json:"msg" validate:"max=1024"`
}

func NewGetSchemaResponseBody() GetSchemaResponseBody {
	v := GetSchemaResponseBody{}
	return v
}

func (s *GetSchemaResponseBody) EscapeStrings() {
	if s.Data != nil {
		s.Data.EscapeStrings()
	}
	s.Detail = html.EscapeString(s.Detail)
	s.Msg = html.EscapeString(s.Msg)
}

func (s *GetSchemaResponseBody) I18n(ctx context.Context) {
	if s.Data != nil {
		s.Data.I18n(ctx)
	}
}

func (GetSchemaResponseBody) JSONFields(fields []string) error {
	check := map[string]bool{
		"code": false,
		"msg":  false,
	}
	err := validator.CheckRequired(check, fields)
	if err != nil {
		return err
	}
	return nil
}
