/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package schemas

import (
	"context"
	"encoding/json"
	"fmt"
	"html"
	"strings"
	"time"

	"ksogit.kingsoft.net/docmini/fx/xfx/conv"
	"ksogit.kingsoft.net/docmini/fx/xfx/el"
	"ksogit.kingsoft.net/docmini/fx/xfx/i18n"
	xfx_json "ksogit.kingsoft.net/docmini/fx/xfx/json"
	"ksogit.kingsoft.net/docmini/fx/xfx/validator"
)

var _ = time.Parse
var _ = html.EscapeString
var _ = validator.CheckRequired
var _ = json.Marshal
var _ = xfx_json.Marshal
var _ = fmt.Println
var _ = conv.ParseInt64
var _ = strings.NewReader
var _ = el.New
var _ = i18n.Translate

type SchemaName struct {
	Options string `json:"options" validate:"max=1024"`
}

func NewSchemaName() SchemaName {
	v := SchemaName{}
	return v
}

func (s *SchemaName) EscapeStrings() {
	s.Options = html.EscapeString(s.Options)
}

func (s *SchemaName) I18n(ctx context.Context) {
}

func (SchemaName) JSONFields(fields []string) error {
	check := map[string]bool{
		"options": false,
	}
	err := validator.CheckRequired(check, fields)
	if err != nil {
		return err
	}
	return nil
}
