/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package schemas

import (
	"context"
	"encoding/json"
	"fmt"
	"html"
	"strings"
	"time"

	"ksogit.kingsoft.net/docmini/fx/xfx/conv"
	"ksogit.kingsoft.net/docmini/fx/xfx/el"
	"ksogit.kingsoft.net/docmini/fx/xfx/i18n"
	xfx_json "ksogit.kingsoft.net/docmini/fx/xfx/json"
	"ksogit.kingsoft.net/docmini/fx/xfx/validator"
)

var _ = time.Parse
var _ = html.EscapeString
var _ = validator.CheckRequired
var _ = json.Marshal
var _ = xfx_json.Marshal
var _ = fmt.Println
var _ = conv.ParseInt64
var _ = strings.NewReader
var _ = el.New
var _ = i18n.Translate

type T2 struct {
}

func NewT2() T2 {
	v := T2{}
	return v
}

func (s *T2) EscapeStrings() {
}

func (s *T2) I18n(ctx context.Context) {
}
