/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package schemas

import (
	"time"
)

type Time time.Time

func (t Time) MarshalJSON() ([]byte, error) {
	data := make([]byte, 0)
	data = time.Time(t).AppendFormat(data, `"2006-01-02T15:04:05Z07:00"`)
	return data, nil
}

func (t *Time) UnmarshalJSON(data []byte) error {
	tm, err := time.Parse(`"2006-01-02T15:04:05Z07:00"`, string(data))
	*t = Time(tm)
	return err
}

func (t Time) MarshalText() ([]byte, error) {
	data := make([]byte, 0)
	data = time.Time(t).AppendFormat(data, `2006-01-02T15:04:05Z07:00`)
	return data, nil
}

func (t *Time) UnmarshalText(data []byte) error {
	tm, err := time.Parse(`2006-01-02T15:04:05Z07:00`, string(data))
	*t = Time(tm)
	return err
}

func (t Time) String() string {
	data := make([]byte, 0)
	data = time.Time(t).AppendFormat(data, `2006-01-02T15:04:05Z07:00`)
	return string(data)
}
