/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package base

import (
	"ksogit.kingsoft.net/docmini/fx/xfx"
	common_m2 "ksogit.kingsoft.net/docmini/mapis/m2"
)

type BaseModules struct {
	M2Module common_m2.CoreAPI
}

func InitBaseModules(app xfx.App, depends ...string) BaseModules {
	base := BaseModules{}

	if len(depends) != 1 {
		panic("params is not valid")
	}
	base.M2Module = app.Module(depends[0]).(common_m2.CoreAPI)

	return base
}
