/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package tag1

import (
	e "ksogit.kingsoft.net/docmini/fx/xfx/econtext"
	"ksogit.kingsoft.net/docmini/fx/xfx/el"
	"ksogit.kingsoft.net/docmini/mapis/tag1/schemas"
)

var _ schemas.Time
var _ e.EContext
var _ el.XError

type CoreAPI interface {
	ExApi
}
