/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package tag1

import (
	e "ksogit.kingsoft.net/docmini/fx/xfx/econtext"
	"ksogit.kingsoft.net/docmini/fx/xfx/el"
	"ksogit.kingsoft.net/docmini/mapis/tag1/httpdef"
)

var _ httpdef.Time
var _ e.EContext
var _ el.XError

type HttpAPI interface {
	CoreAPI
	GetSchema(ctx e.EContext, r *httpdef.GetSchemaRequest) (*httpdef.GetSchemaResponse, el.XError)
}
