/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package tag1

import (
	e "ksogit.kingsoft.net/docmini/fx/xfx/econtext"
	"ksogit.kingsoft.net/docmini/fx/xfx/el"

	"ksogit.kingsoft.net/docmini/mapis/interceptor"
)

var _ e.EContext
var _ el.XError
var _ interceptor.Interceptor

var (
	globalGetSchemaInterceptors []GetSchemaInterceptorSchema

	globalCommInterceptors []interceptor.InterceptorSchema
)

func RegisterGetSchemaInterceptor(interceptor GetSchemaInterceptorSchema) {
	globalGetSchemaInterceptors = append(globalGetSchemaInterceptors, interceptor)
}

func RegisterInterceptor(interceptor interceptor.InterceptorSchema) {
	globalCommInterceptors = append(globalCommInterceptors, interceptor)
}

func GlobalCommInterceptors() []interceptor.InterceptorSchema {
	return globalCommInterceptors
}
func GlobalGetSchemaInterceptors() []GetSchemaInterceptorSchema {
	return globalGetSchemaInterceptors
}
