/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package tag1

import (
	"ksogit.kingsoft.net/docmini/fx/xfx"
	e "ksogit.kingsoft.net/docmini/fx/xfx/econtext"
	"ksogit.kingsoft.net/docmini/fx/xfx/el"
	"ksogit.kingsoft.net/docmini/mapis/interceptor"
	"ksogit.kingsoft.net/docmini/mapis/tag1/httpdef"
	"ksogit.kingsoft.net/docmini/mapis/tag1/schemas"
)

var _ e.EContext
var _ el.XError
var _ schemas.Time
var _ httpdef.Time
var _ xfx.Context

var MAPINames = []string{}

type GetSchemaHandler func(ctx e.EContext, r *httpdef.GetSchemaRequest) (*httpdef.GetSchemaResponse, el.XError)
type GetSchemaInterceptor func(ctx e.EContext, r *httpdef.GetSchemaRequest, apiInfo *interceptor.ApiInfo, handler GetSchemaHandler) (*httpdef.GetSchemaResponse, el.XError)

type GetSchemaInterceptorSchema interface {
	Name() string
	Interceptor(app xfx.App, module xfx.Module) GetSchemaInterceptor
}

func ToGetSchemaInterceptor(comm interceptor.Interceptor) GetSchemaInterceptor {
	return func(ctx e.EContext, r *httpdef.GetSchemaRequest, apiInfo *interceptor.ApiInfo, handler GetSchemaHandler) (*httpdef.GetSchemaResponse, el.XError) {
		done, err := comm.Do(ctx, apiInfo, r)
		if err != nil {
			return nil, err
		}
		resp, respErr := handler(ctx, r)
		err2 := done(ctx, apiInfo, r, resp, err)
		if err2 != nil {
			return nil, err2
		}
		return resp, respErr
	}
}
