/*-----------------------------------------------------------------------------------
 * Kingsoft Office Enterprise Cloud Services.
 * Copyright (c) Kingsoft Office,  All rights reserved.
 *-----------------------------------------------------------------------------------*/
// Code generated by xfx; DO NOT EDIT.

package srv

import (
	"ksogit.kingsoft.net/docmini/fx/xfx/econtext"
	"ksogit.kingsoft.net/docmini/fx/xfx/validator"
	"ksogit.kingsoft.net/docmini/mapis/tag1/httpdef"
	"tmp/modules"
)

var _ = validator.Validate

func NewGetSchemaService(module *modules.Tag1Module) httpdef.GetSchemaFunc {
	return func(ctx econtext.EContext, request *httpdef.GetSchemaRequest) (*httpdef.GetSchemaResponse, error) {
		err := validator.Validate(request)
		if err != nil {
			return nil, err
		}

		return module.GetSchema(ctx, request)
	}
}
